In [290]:
import pandas as pd
import numpy as np

In [291]:
df = pd.read_json('.data/joined_data.json').set_index('index')
df.sample(3)

chance_of_playing_next_round  chance_of_playing_this_round  \
index                                                               
472                             NaN                           NaN   
110                             NaN                           NaN   
620                             NaN                           NaN   

       dreamteam_count  element_type  event_points  form  in_dreamteam news  \
index                                                                         
472                  0             4             0   0.5         False        
110                  1             2             0   0.0         False        
620                  0             3             0   0.0         False        

      news_added  now_cost  points_per_game  selected_by_percent status  team  \
index                                                                           
472         None        50              2.0                  1.5      a    18   
110         None        44              3.2                  1.7      a     5   
620         None        45              0.5                  0.0      a    11   

       total_points  transfers_in  transfers_out  value_form  value_season  \
index                                                                        
472              34        434485         392486         0.1           6.8   
110              55        272821         326039         0.0          12.5   
620               1           705            568         0.0           0.2   

       minutes  goals_scored  assists  clean_sheets  goals_conceded  \
index                                                                 
472        695             2        1             1              21   
110       1514             1        3             3              27   
620         65             0        0             0               1   

       own_goals  penalties_saved  penalties_missed  yellow_cards  red_cards  \
index                                                                          
472            0                0                 0             0          0   
110            0                0                 0             2          0   
620            0                0                 0             1          0   

       saves  bonus  bps  influence  creativity  threat  ict_index  \
index                                                                
472        0      2  139      152.6       239.7     254       64.6   
110        0      5  292      353.2       235.7      81       67.1   
620        0      0    4        2.8         2.4       0        0.6   

       influence_rank  creativity_rank  threat_rank  ict_index_rank  \
index                                                                 
472               279              105          110             155   
110               100              109          257             151   
620               477              428          611             484   

       corners_and_indirect_freekicks_order  direct_freekicks_order  \
index                                                                 
472                                     NaN                     3.0   
110                                     NaN                     NaN   
620                                     NaN                     NaN   

       penalties_order                   player_name  games        xG  \
index                                                                   
472                NaN  Juan Camilo Hernández Suárez     17  1.581986   
110                NaN                Matthew Lowton     17  0.713878   
620                NaN                  Tyler Morton      2  0.000000   

             xA  shots  key_passes  npg      npxG   xGChain  xGBuildup  
index                                                                   
472    1.229331     21          17    2  1.581986  2.859059   1.140872  
110    2.086637      8          15    1  0.713878  4.048127   3

In [292]:
df_left = df[df['chance_of_playing_next_round'] == df['chance_of_playing_next_round'].isna()]
df_left.sample(3)

chance_of_playing_next_round  chance_of_playing_this_round  \
index                                                               
268                             0.0                           0.0   
4                               0.0                           0.0   
497                             0.0                           0.0   

       dreamteam_count  element_type  event_points  form  in_dreamteam  \
index                                                                    
268                  1             3             0   0.0         False   
4                    0             4             0   0.0         False   
497                  0             3             0   0.0         False   

                                                    news  \
index                                                      
268                             Transferred to Barcelona   
4                            Left club by mutual consent   
497    Joined Stoke City on loan until the end of the...   

                        news_added  now_cost  points_per_game  \
index                                                           
268    2021-10-14T12:00:10.242757Z        67              6.5   
4      2022-02-02T08:21:28.428217Z        96              3.1   
497    2022-01-21T13:30:20.197682Z        50              1.0   

       selected_by_percent status  team  total_points  transfers_in  \
index                                                                 
268                    2.0      u    12            26       1732247   
4                      1.4      u     1            44        742898   
497                    0.0      u     2             1          1105   

       transfers_out  value_form  value_season  minutes  goals_scored  \
index                                                                   
268          1829557         0.0           3.9      303             2   
4             889021         0.0           4.6     1036             4   
497             2472         0.0           0.2        4             0   

       assists  clean_sheets  goals_conceded  own_goals  penalties_saved  \
index                                                                      
268          1             3               1          0                0   
4            1             6              16          0                0   
497          0             0               0          0                0   

       penalties_missed  yellow_cards  red_cards  saves  bonus  bps  \
index                                                                 
268                   0             0          0      0      2   65   
4                     2             3          0      0      7  131   
497                   0             0          0      0      0    0   

       influence  creativity  threat  ict_index  influence_rank  \
index                                                             
268         88.6        30.0     204       32.3             347   
4          217.6       132.4     582       92.9             215   
497          0.0         0.0       0        0.0             684   

       creativity_rank  threat_rank  ict_index_rank  \
index                                                 
268                348          138             288   
4                  185           26              69   
497                682          676             684   

       corners_and_indirect_freekicks_order  direct_freekicks_order  \
index                                                                 
268                                     NaN                     NaN   
4                                       NaN                     NaN   
497                                     NaN                     NaN   

       penalties_order                player_name  games        xG        xA  \
index                                                                          
268                NaN              Ferran Torres      4  2.512166  0.021644

In [293]:
injuries = []
for player in df_left.iterrows():
    if ('injury' in player[1]['news'].lower() or 'suspended' in player[1]['news'].lower()) and 'unknown ' not in player[1]['news'].lower():
        injuries.append(player[0])
        
print(injuries)

[26, 41, 45, 59, 612, 135, 161, 163, 173, 175, 179, 201, 205, 209, 218, 184, 191, 296, 465, 314, 327, 567, 618]


In [294]:
df_left = df_left.drop(index=injuries)
df_left.sample(3)

chance_of_playing_next_round  chance_of_playing_this_round  \
index                                                               
263                             0.0                           0.0   
37                              0.0                           0.0   
602                             0.0                           0.0   

       dreamteam_count  element_type  event_points  form  in_dreamteam  \
index                                                                    
263                  2             4             0   0.3         False   
37                   0             3             0   0.0         False   
602                  0             4             0   0.0         False   

                                                    news  \
index                                                      
263                  Muscle injury - Unknown return date   
37     Joined Istanbul Basaksehir on loan until the e...   
602    Joined Heart of Midlothian on loan until the e...   

                        news_added  now_cost  points_per_game  \
index                                                           
263    2022-02-05T10:00:10.226374Z        85              3.7   
37     2022-01-01T17:00:18.616625Z        54              1.0   
602    2022-01-26T18:00:14.812256Z        45              2.0   

       selected_by_percent status  team  total_points  transfers_in  \
index                                                                 
263                    5.1      i    12            71       2179417   
37                     0.0      u     2             1          3656   
602                    0.3      u     8             2         69799   

       transfers_out  value_form  value_season  minutes  goals_scored  \
index                                                                   
263          2152969         0.0           8.4     1320             2   
37              3810         0.0           0.2       10             0   
602            49928         0.0           0.4       61             0   

       assists  clean_sheets  goals_conceded  own_goals  penalties_saved  \
index                                                                      
263          7             9               8          0                0   
37           0             0               1          0                0   
602          0             1               0          0                0   

       penalties_missed  yellow_cards  red_cards  saves  bonus  bps  \
index                                                                 
263                   0             0          0      0      8  258   
37                    0             0          0      0      0    4   
602                   0             0          0      0      0    6   

       influence  creativity  threat  ict_index  influence_rank  \
index                                                             
263        297.0       379.7     711      139.0             144   
37           1.8         2.0      10        1.4             485   
602          6.4         0.4       0        0.7             461   

       creativity_rank  threat_rank  ict_index_rank  \
index                                                 
263                 46           12              25   
37                 429          390             472   
602                458          588             480   

       corners_and_indirect_freekicks_order  direct_freekicks_order  \
index                                                                 
263                                     NaN                     NaN   
37                                      NaN                     NaN   
602                                     NaN                     NaN   

       penalties_order                   player_name  games        xG  \
index                                                                   
263                NaN     Gabriel Fernando de Jesus     19  5.141318   
37               

In [295]:
df = df.drop(index=df_left.index)
df.sample(3)

chance_of_playing_next_round  chance_of_playing_this_round  \
index                                                               
579                           100.0                         100.0   
382                           100.0                         100.0   
171                           100.0                         100.0   

       dreamteam_count  element_type  event_points  form  in_dreamteam news  \
index                                                                         
579                  5             4            10   3.0         False        
382                  0             2             1   2.8         False        
171                  0             3             3   1.3         False        

                        news_added  now_cost  points_per_game  \
index                                                           
579    2022-01-21T16:00:18.812016Z       125              4.6   
382    2021-12-29T00:30:20.230216Z        43              1.9   
171    2022-01-15T18:30:13.496623Z        43              2.5   

       selected_by_percent status  team  total_points  transfers_in  \
index                                                                 
579                   25.8      a    13            97       6505954   
382                    0.2      a    18            31         28480   
171                    3.6      a     8            48       1027297   

       transfers_out  value_form  value_season  minutes  goals_scored  \
index                                                                   
579          4772992         0.2           7.8     1658             9   
382            29531         0.7           7.2     1217             0   
171           906644         0.3          11.2     1627             0   

       assists  clean_sheets  goals_conceded  own_goals  penalties_saved  \
index                                                                      
579          3             6              26          0                0   
382          3             1              27          0                0   
171          3             4              30          0                0   

       penalties_missed  yellow_cards  red_cards  saves  bonus  bps  \
index                                                                 
579                   0             4          0      0     17  338   
382                   0             1          0      0      1  223   
171                   0             4          0      0      2  246   

       influence  creativity  threat  ict_index  influence_rank  \
index                                                             
579        454.8       288.3    1034      177.3              42   
382        263.2       197.4      28       49.0             170   
171        304.0       189.3      57       55.2             138   

       creativity_rank  threat_rank  ict_index_rank  \
index                                                 
579                 73            3              11   
382                134          351             219   
171                141          302             193   

       corners_and_indirect_freekicks_order  direct_freekicks_order  \
index                                                                 
579                                     NaN                     1.0   
382                                     1.0                     NaN   
171                                     NaN                     NaN   

       penalties_order                          player_name  games         xG  \
index                                                                           
579                1.0  Cristiano Ronaldo dos Santos Aveiro     21  11.932843   
382                NaN                Francisco Femenía Far     16   0.030327   
171                NaN               Allan Marques Loureiro     19   0.200633   

             xA  shots  key_passes  npg       npxG    xGChain  xGBuildup  
index                          

In [296]:
df.columns 

Index(['chance_of_playing_next_round', 'chance_of_playing_this_round',
       'dreamteam_count', 'element_type', 'event_points', 'form',
       'in_dreamteam', 'news', 'news_added', 'now_cost', 'points_per_game',
       'selected_by_percent', 'status', 'team', 'total_points', 'transfers_in',
       'transfers_out', 'value_form', 'value_season', 'minutes',
       'goals_scored', 'assists', 'clean_sheets', 'goals_conceded',
       'own_goals', 'penalties_saved', 'penalties_missed', 'yellow_cards',
       'red_cards', 'saves', 'bonus', 'bps', 'influence', 'creativity',
       'threat', 'ict_index', 'influence_rank', 'creativity_rank',
       'threat_rank', 'ict_index_rank', 'corners_and_indirect_freekicks_order',
       'direct_freekicks_order', 'penalties_order', 'player_name', 'games',
       'xG', 'xA', 'shots', 'key_passes', 'npg', 'npxG', 'xGChain',
       'xGBuildup'],
      dtype='object')

In [297]:
pd.get_dummies(df['news'])

Ankle injury - 25% chance of playing  \
index                                            
1      0                                     0   
5      1                                     0   
6      1                                     0   
7      1                                     0   
12     1                                     0   
...   ..                                   ...   
475    1                                     0   
547    1                                     0   
583    1                                     0   
685    1                                     0   
689    1                                     0   

       Ankle injury - 50% chance of playing  \
index                                         
1                                         0   
5                                         0   
6                                         0   
7                                         0   
12                                        0   
...                                     ...   
475                                       0   
547                                       0   
583                                       0   
685                                       0   
689                                       0   

       Ankle injury - 75% chance of playing  \
index                                         
1                                         0   
5                                         0   
6                                         0   
7                                         0   
12                                        0   
...                                     ...   
475                                       0   
547                                       0   
583                                       0   
685                                       0   
689                                       0   

       Calf injury - 50% chance of playing  \
index                                        
1                                        0   
5                                        0   
6                                        0   
7                                        0   
12                                       0   
...                                    ...   
475                                      0   
547                                      0   
583                                      0   
685                                      0   
689                                      0   

       Calf injury - Expected back 07 May  \
index                                       
1                                       0   
5                                       0   
6                                       0   
7                                       0   
12                                      0   
...                                   ...   
475                                     0   
547                                     0   
583                                     0   
685                                     0   
689                                     0   

       Foot injury - 25% chance of playing  \
index                                        
1                                        0   
5                                        0   
6                                        0   
7                                        0   
12                                       0   
...                                    ...   
475                                      0   
547                                      0   
583                                      0   
685                                      0   
689                                      0   

       Groin Injury - 50% chance of playing  \
index                                         
1                                         0   
5                                         0   
6                                         0   
7                                         0   
12                                        0   
...                   

In [298]:
for player in df.iterrows():
    if player[1]['news'] == '':
        pass
    if ('injury' in player[1]['news'].lower() or 'suspended' in player[1]['news'].lower()) and 'unknown ' not in player[1]['news'].lower():
        injuries.append(player[0])
        

In [299]:
# Created my own dummy variables
df['75%'] = df['news'].str.contains('75%')*1
df['50%'] = df['news'].str.contains('50%')*1
df['25%'] = df['news'].str.contains('25%')*1

df['unknown'] = df['news'].str.lower().str.contains('unknown%')*1
df['expected_back'] = df['news'].str.lower().str.contains('expected back')*1
df['suspended'] = df['news'].str.lower().str.contains('suspended')*1

# df['75%'] = np.where(df['news'].str.contains('75%'), 1, 0)
# df['50%'] = np.where(df['news'].str.contains('50%'), 1, 0)
# df['25%'] = np.where(df['news'].str.contains('25%'), 1, 0)
# df['unkown'] = np.where(df['news'].str.lower().str.contains('unkown'), 1, 0)
# df['expected_back'] = np.where(df['news'].str.lower().str.contains('expected back'), 1, 0)
# df['suspended'] = np.where(df['news'].str.lower().str.contains('suspended'), 1, 0)
df = df.drop(['news','news_added'], axis=1)
df

chance_of_playing_next_round  chance_of_playing_this_round  \
index                                                               
1                              75.0                          75.0   
5                             100.0                         100.0   
6                             100.0                         100.0   
7                             100.0                         100.0   
12                            100.0                         100.0   
...                             ...                           ...   
475                             NaN                           NaN   
547                             NaN                           NaN   
583                           100.0                          75.0   
685                             NaN                           NaN   
689                             NaN                           NaN   

       dreamteam_count  element_type  event_points  form  in_dreamteam  \
index                                                                    
1                    0             1             0   0.0         False   
5                    0             2             0   3.0         False   
6                    1             4             0   3.5         False   
7                    0             3             0   1.0         False   
12                   0             3             0   0.0         False   
...                ...           ...           ...   ...           ...   
475                  4             1            10   4.3         False   
547                  0             3             3   1.0         False   
583                  1             4             1   0.3         False   
685                  0             2             0   0.3         False   
689                  0             3             0   0.3         False   

       now_cost  points_per_game  selected_by_percent status  team  \
index                                                                
1            45              1.3                  0.8      d     1   
5            42              1.6                  0.2      a     1   
6            83              3.1                  4.5      a     1   
7            48              1.8                  0.3      a     1   
12           44              1.6                  0.3      a     1   
...         ...              ...                  ...    ...   ...   
475          52              4.7                  7.6      a    20   
547          44              2.0                  0.1      a    20   
583          54              3.2                  2.5      a    20   
685          45              1.5                  0.0      a    20   
689          55              1.0                  0.0      a    20   

       total_points  transfers_in  transfers_out  value_form  value_season  \
index                                                                        
1                 4         63640         188156         0.0           0.9   
5                 8         14748          26229         0.7           1.9   
6                53        967727         810760         0.4           6.4   
7                20         26690          86255         0.2           4.2   
12               11         35304          71433         0.0           2.5   
...             ...           ...            ...         ...           ...   
475             108       1095942         522312         0.8          20.8   
547               4         11358          10872         0.2           0.9   
583              48       1732414        1596323         0.1           8.9   
685               3           324            170         0.1           0.7   
689               1           394            171         0.1           0.2   

       minutes  goals_scored  assists  clean_sheets  goals_conceded  \
index                                                                 
1          270             0        0             0               9   
5      

In [300]:
# pd.set_option('display.max_columns', None)
# df[df['chance_of_playingb_this_round'].isnull()]

In [439]:
df[df['player_name'].str.contains('Leno')]
to_drop = [#'chance_of_playing_next_round', 'chance_of_playing_this_round', 'dreamteam_count', 'element_type',
       'event_points', 'form',
       'in_dreamteam', 'now_cost', 'points_per_game', 'selected_by_percent',
       'status', 'team',
       'total_points', #THIS COLUMN IS A LITTLE BIT NAUGHTY AS GIVE HINT INTO FUTURE using cumsum instead
       'transfers_in', 'transfers_out',
       'value_form', 'value_season', 'minutes', 'goals_scored', 'assists',
       'clean_sheets', 'goals_conceded', 'own_goals', 'penalties_saved',
       'penalties_missed', 'yellow_cards', 'red_cards', 'saves', 'bonus',
       'bps', 'influence', 'creativity', 'threat', 'ict_index',
       #'influence_rank', 'creativity_rank', 'threat_rank', 'ict_index_rank',
       #'corners_and_indirect_freekicks_order', 'direct_freekicks_order',
       #'penalties_order', 'player_name',
       'games',

       # Need to drop these columns for time being as they give ML model a hint into future
       'xG', 'xA', 'shots', 'key_passes', 'npg', 'npxG', 'xGChain', 'xGBuildup',
       '75%', '50%', '25%', 'unknown', 'expected_back', 'suspended'
       ]
df.drop(columns=to_drop)

chance_of_playing_next_round  chance_of_playing_this_round  \
index                                                               
1                              75.0                          75.0   
5                             100.0                         100.0   
6                             100.0                         100.0   
7                             100.0                         100.0   
12                            100.0                         100.0   
...                             ...                           ...   
475                             NaN                           NaN   
547                             NaN                           NaN   
583                           100.0                          75.0   
685                             NaN                           NaN   
689                             NaN                           NaN   

       dreamteam_count  element_type  influence_rank  creativity_rank  \
index                                                                   
1                    0             1             351              590   
5                    0             2             391              286   
6                    1             4             173               93   
7                    0             3             289              177   
12                   0             3             396              290   
...                ...           ...             ...              ...   
475                  4             1               7              347   
547                  0             3             465              381   
583                  1             4             231              186   
685                  0             2             400              432   
689                  0             3             470              380   

       threat_rank  ict_index_rank  corners_and_indirect_freekicks_order  \
index                                                                      
1              569             413                                   NaN   
5              416             393                                   NaN   
6               50              65                                   NaN   
7              259             263                                   NaN   
12             404             391                                   NaN   
...            ...             ...                                   ...   
475            680             154                                   NaN   
547            546             459                                   4.0   
583            120             189                                   NaN   
685            640             436                                   NaN   
689            332             428                                   NaN   

       direct_freekicks_order  penalties_order                     player_name  
index                                                                           
1                         NaN              NaN                      Bernd Leno  
5                         NaN              NaN                   Cédric Soares  
6                         NaN              2.0             Alexandre Lacazette  
7                         4.0              NaN                    Granit Xhaka  
12                        NaN              NaN   Mohamed Naser El Sayed Elneny  
...                       ...              ...                             ...  
475                       NaN              NaN             José Malheiro de Sá  
547                       NaN              NaN                     Luke Cundle  
583                       NaN              NaN                  Hee-Chan Hwang  
685                       NaN              NaN              Toti António Gomes  
689                       NaN              NaN  Francisco Jorge Tomás Oliveira  

[444 rows x 12 columns]

# Player history data

In [330]:
import json

with open('.data/history.json', 'r') as f:
  hist_data = json.load(f)

In [331]:
# ensuring player id is an integer
hist_data = {int(key):value for key,value in hist_data.items()}

In [332]:
print(f"Number of players in history json {len(hist_data.keys())}")
print(f"Number of players in dataframe {len(df.index)}")
print(f"Number of matches {len([id for id in list(df.index) if id in hist_data.keys()])}")

Number of players in history json 707
Number of players in dataframe 444
Number of matches 444


In [333]:
# future games, gameweeks
future = pd.DataFrame(hist_data[413]['fixtures'])
future

id     code  team_h team_h_score  team_a team_a_score  event  finished  \
0   259  2210529      19         None      14         None     26     False   
1   270  2210540      19         None      20         None     27     False   
2   274  2210544      11         None      19         None     28     False   
3   290  2210560      19         None       2         None     29     False   
4   298  2210568      17         None      19         None     30     False   
5   309  2210579      19         None       8         None     31     False   
6   313  2210583       3         None      19         None     32     False   
7   329  2210599      19         None       5         None     33     False   
8   335  2210605       6         None      19         None     34     False   
9   349  2210619      19         None       1         None     35     False   
10  360  2210630      15         None      19         None     36     False   
11  369  2210639      19         None      12         None     37     False   
12  373  2210643       4         None      19         None     38     False   

    minutes  provisional_start_time          kickoff_time   event_name  \
0         0                   False  2022-02-19T12:30:00Z  Gameweek 26   
1         0                   False  2022-02-27T14:00:00Z  Gameweek 27   
2         0                   False  2022-03-05T17:30:00Z  Gameweek 28   
3         0                   False  2022-03-13T14:00:00Z  Gameweek 29   
4         0                   False  2022-03-20T14:00:00Z  Gameweek 30   
5         0                   False  2022-04-02T14:00:00Z  Gameweek 31   
6         0                   False  2022-04-09T14:00:00Z  Gameweek 32   
7         0                   False  2022-04-16T14:00:00Z  Gameweek 33   
8         0                   False  2022-04-23T14:00:00Z  Gameweek 34   
9         0                   False  2022-04-30T14:00:00Z  Gameweek 35   
10        0                   False  2022-05-07T14:00:00Z  Gameweek 36   
11        0                   False  2022-05-15T14:00:00Z  Gameweek 37   
12        0                   False  2022-05-22T15:00:00Z  Gameweek 38   

    is_home  difficulty  
0      True           2  
1      True           3  
2     False           5  
3      True           3  
4     False           4  
5      True           2  
6     False           2  
7      True           2  
8     False           5  
9      True           3  
10    False           2  
11     True           5  
12    False           3

In [334]:
history = pd.DataFrame(hist_data[413]['history'])
history

element  fixture  opponent_team  total_points  was_home  \
0       413        9             14            13     False   
1       413       20              9            16      True   
2       413       28              7            11      True   
3       413       39             16            -1     False   
4       413       49             13             0      True   
5       413       56             10             8     False   
6       413       69              3             2      True   
7       413       74              8             1     False   
8       413       90             17             7      True   
9       413       91              2             2     False   
10      413      110             11             2      True   
11      413      120             20             2     False   
12      413      129             12             2     False   
13      413      136              4             1      True   
14      413      149              6             5      True   
15      413      154              5             2     False   
16      413      161              1             2     False   
17      413      189             16             5      True   
18      413      200             18             5     False   
19      413      204              7             7     False   
20      413      179             15             2      True   
21      413      219             10             4      True   
22      413      228             13             2     False   
23      413      235             18             2      True   
24      413      245              9             2     False   

            kickoff_time  team_h_score  team_a_score  round  minutes  \
0   2021-08-15T13:00:00Z             2             4      1       90   
1   2021-08-23T19:00:00Z             4             1      2       88   
2   2021-08-28T14:00:00Z             2             2      3       90   
3   2021-09-11T14:00:00Z             0             0      4       90   
4   2021-09-19T13:00:00Z             1             2      5        0   
5   2021-09-25T14:00:00Z             1             2      6       90   
6   2021-10-03T13:00:00Z             1             2      7       90   
7   2021-10-17T13:00:00Z             0             1      8       90   
8   2021-10-24T13:00:00Z             1             0      9       90   
9   2021-10-31T16:30:00Z             1             4     10       90   
10  2021-11-07T16:30:00Z             3             2     11       90   
11  2021-11-20T15:00:00Z             1             0     12       90   
12  2021-11-28T14:00:00Z             2             1     13       90   
13  2021-12-01T19:30:00Z             1             1     14       90   
14  2021-12-04T12:30:00Z             3             2     15       90   
15  2021-12-12T14:00:00Z             0             0     16       90   
16  2021-12-15T20:00:00Z             2             0     17       90   
17  2021-12-26T15:00:00Z             2             3     19       45   
18  2021-12-28T15:00:00Z             1             4     20       90   
19  2022-01-01T17:30:00Z             2             3     21       90   
20  2022-01-12T19:45:00Z             2             0     21       87   
21  2022-01-16T14:00:00Z             2             3     22       90   
22  2022-01-22T15:00:00Z             1             0     23       90   
23  2022-02-08T19:45:00Z             1             0     24       90   
24  2022-02-13T16:30:00Z             2             2     25       90   

    goals_scored  assists  clean_sheets  goals_conceded  own_goals  \
0              1        2             0               2          0   
1              2        1             0               1          0   
2              1        1             0               2          0   
3              0        0             1               0          0   
4              0        0             0               0          0   
5              1        0             0               1          0   
6 

In [335]:
team_cols = {i:'opponent_team_is_'+str(i) for i in np.arange(1,21)}
history[list(team_cols.values())] = 0
history.sample(3)

element  fixture  opponent_team  total_points  was_home  \
19      413      204              7             7     False   
12      413      129             12             2     False   
10      413      110             11             2      True   

            kickoff_time  team_h_score  team_a_score  round  minutes  \
19  2022-01-01T17:30:00Z             2             3     21       90   
12  2021-11-28T14:00:00Z             2             1     13       90   
10  2021-11-07T16:30:00Z             3             2     11       90   

    goals_scored  assists  clean_sheets  goals_conceded  own_goals  \
19             1        0             0               2          0   
12             0        0             0               2          0   
10             0        0             0               2          0   

    penalties_saved  penalties_missed  yellow_cards  red_cards  saves  bonus  \
19                0                 0             0          0      0      1   
12                0                 0             0          0      0      0   
10                0                 0             0          0      0      0   

    bps influence creativity threat ict_index  value  transfers_balance  \
19   28      40.2       15.8   53.0      10.9     78             569305   
12    0       2.8        1.1    8.0       1.2     81            -333147   
10    4       0.0        2.2   18.0       2.0     82            -111803   

    selected  transfers_in  transfers_out  opponent_team_is_1  \
19   3880687        630427          61122                   0   
12   3852686         61659         394806                   0   
10   4016151        106217         218020                   0   

    opponent_team_is_2  opponent_team_is_3  opponent_team_is_4  \
19                   0                   0                   0   
12                   0                   0                   0   
10                   0                   0                   0   

    opponent_team_is_5  opponent_team_is_6  opponent_team_is_7  \
19                   0                   0                   0   
12                   0                   0                   0   
10                   0                   0                   0   

    opponent_team_is_8  opponent_team_is_9  opponent_team_is_10  \
19                   0                   0                    0   
12                   0                   0                    0   
10                   0                   0                    0   

    opponent_team_is_11  opponent_team_is_12  opponent_team_is_13  \
19                    0                    0                    0   
12                    0                    0                    0   
10                    0                    0                    0   

    opponent_team_is_14  opponent_team_is_15  opponent_team_is_16  \
19                    0                    0                    0   
12                    0                    0                    0   
10                    0                    0                    0   

    opponent_team_is_17  opponent_team_is_18  opponent_team_is_19  \
19                    0                    0                    0   
12                    0                    0                    0   
10                    0                    0                    0   

    opponent_team_is_20  
19                    0  
12                    0  
10                    0

In [336]:
opponent_dummies = pd.get_dummies(history['opponent_team']).rename(columns=team_cols)
opponent_dummies.sample(3)

opponent_team_is_1  opponent_team_is_2  opponent_team_is_3  \
14                   0                   0                   0   
4                    0                   0                   0   
18                   0                   0                   0   

    opponent_team_is_4  opponent_team_is_5  opponent_team_is_6  \
14                   0                   0                   1   
4                    0                   0                   0   
18                   0                   0                   0   

    opponent_team_is_7  opponent_team_is_8  opponent_team_is_9  \
14                   0                   0                   0   
4                    0                   0                   0   
18                   0                   0                   0   

    opponent_team_is_10  opponent_team_is_11  opponent_team_is_12  \
14                    0                    0                    0   
4                     0                    0                    0   
18                    0                    0                    0   

    opponent_team_is_13  opponent_team_is_14  opponent_team_is_15  \
14                    0                    0                    0   
4                     1                    0                    0   
18                    0                    0                    0   

    opponent_team_is_16  opponent_team_is_17  opponent_team_is_18  \
14                    0                    0                    0   
4                     0                    0                    0   
18                    0                    0                    1   

    opponent_team_is_20  
14                    0  
4                     0  
18                    0

## Function for linking fixture difficulty

In [337]:
# FUNCTION
import requests
url = "https://fantasy.premierleague.com/api/bootstrap-static/"

response = requests.get(url)
team_df = pd.DataFrame(response.json()['teams']).set_index('id').drop(columns=[
       'code', 'draw', 'form',
       # 'id',
       'loss', 'name', 'played', 'points',
       'position', 'short_name',
       # 'strength', 
       'team_division', 'unavailable',
       'win',
       #'strength_overall_home', 'strength_overall_away',
       #'strength_attack_home', 'strength_attack_away', 'strength_defence_home',
       #'strength_defence_away',
       'pulse_id'])

In [338]:
list(team_cols.values())

['opponent_team_is_1',
 'opponent_team_is_2',
 'opponent_team_is_3',
 'opponent_team_is_4',
 'opponent_team_is_5',
 'opponent_team_is_6',
 'opponent_team_is_7',
 'opponent_team_is_8',
 'opponent_team_is_9',
 'opponent_team_is_10',
 'opponent_team_is_11',
 'opponent_team_is_12',
 'opponent_team_is_13',
 'opponent_team_is_14',
 'opponent_team_is_15',
 'opponent_team_is_16',
 'opponent_team_is_17',
 'opponent_team_is_18',
 'opponent_team_is_19',
 'opponent_team_is_20']

In [353]:
history[['opponent_team','was_home']]

opponent_team  was_home
0              14     False
1               9      True
2               7      True
3              16     False
4              13      True
5              10     False
6               3      True
7               8     False
8              17      True
9               2     False
10             11      True
11             20     False
12             12     False
13              4      True
14              6      True
15              5     False
16              1     False
17             16      True
18             18     False
19              7     False
20             15      True
21             10      True
22             13     False
23             18      True
24              9     False

In [340]:
team_df.columns

Index(['strength', 'strength_overall_home', 'strength_overall_away',
       'strength_attack_home', 'strength_attack_away', 'strength_defence_home',
       'strength_defence_away'],
      dtype='object')

In [372]:
oppenent_home = team_df.loc[history['opponent_team'],['strength', 'strength_overall_home',
       'strength_attack_home', 'strength_defence_home']]
oppenent_home.columns = oppenent_home.columns.map(lambda x : 'opponent_' + '_'.join(x.split('_')[0:2]))
len(oppenent_home)

25

In [373]:

oppenent_away = team_df.loc[history['opponent_team'],['strength', 'strength_overall_away',
       'strength_attack_away', 'strength_defence_away']]
oppenent_away.columns = oppenent_away.columns.map(lambda x : 'opponent_' + '_'.join(x.split('_')[0:2]))
len(oppenent_away)

25

## Concat the fixuture difficulty

In [384]:
#history['opponent_strength','opponent_strength_overall','opponent_strength_attack','opponent_strength_defence'] =
fixture_difficulty = oppenent_home.where(history['was_home'], oppenent_away).reset_index().drop(columns=['id'])
history = pd.concat([history,fixture_difficulty], axis=1)

In [385]:
history[list(opponent_dummies.columns)] = opponent_dummies
history = history.drop(['element','fixture','kickoff_time','opponent_team'], axis=1)
history

total_points  was_home  team_h_score  team_a_score  round  minutes  \
0             13     False             2             4      1       90   
1             16      True             4             1      2       88   
2             11      True             2             2      3       90   
3             -1     False             0             0      4       90   
4              0      True             1             2      5        0   
5              8     False             1             2      6       90   
6              2      True             1             2      7       90   
7              1     False             0             1      8       90   
8              7      True             1             0      9       90   
9              2     False             1             4     10       90   
10             2      True             3             2     11       90   
11             2     False             1             0     12       90   
12             2     False             2             1     13       90   
13             1      True             1             1     14       90   
14             5      True             3             2     15       90   
15             2     False             0             0     16       90   
16             2     False             2             0     17       90   
17             5      True             2             3     19       45   
18             5     False             1             4     20       90   
19             7     False             2             3     21       90   
20             2      True             2             0     21       87   
21             4      True             2             3     22       90   
22             2     False             1             0     23       90   
23             2      True             1             0     24       90   
24             2     False             2             2     25       90   

    goals_scored  assists  clean_sheets  goals_conceded  own_goals  \
0              1        2             0               2          0   
1              2        1             0               1          0   
2              1        1             0               2          0   
3              0        0             1               0          0   
4              0        0             0               0          0   
5              1        0             0               1          0   
6              0        0             0               2          0   
7              0        0             1               0          0   
8              1        0             1               0          0   
9              0        0             0               1          0   
10             0        0             0               2          0   
11             0        0             0               1          0   
12             0        0             0               2          0   
13             0        0             0               1          0   
14             0        1             0               2          0   
15             0        0             1               0          0   
16             0        0             0               2          0   
17             1        0             0               2          0   
18             0        1             0               1          0   
19             1        0             0               2          0   
20             0        0             1               0          0   
21             0        1             0               3          0   
22             0        0             0               1          0   
23             0        0             1               0          0   
24             0        0             0               2          0   

    penalties_saved  penalties_missed  yellow_cards  red_cards  saves  bonus  \
0                 0                 1             0          0      0      3   
1                 0                 0             0          0      0      3   
2                 

In [386]:
history['goals_for'] = history['team_h_score'].where(history['was_home'], history['team_a_score'])
history['goals_against'] = history['team_a_score'].where(history['was_home'], history['team_h_score'])
history = history.drop(columns=['team_h_score','team_a_score'])

In [430]:
columns_to_drop = ['value', 'transfers_balance', 'selected', 'transfers_in','transfers_out','opponent_strength', 'opponent_strength_overall',
       'opponent_strength_attack', 'opponent_strength_defence']
new_history = pd.concat([history.groupby('round').sum().drop(columns=columns_to_drop), history.groupby('round')[columns_to_drop].mean()], axis=1)
new_history

total_points  was_home  minutes  goals_scored  assists  clean_sheets  \
round                                                                         
1                13         0       90             1        2             0   
2                16         1       88             2        1             0   
3                11         1       90             1        1             0   
4                -1         0       90             0        0             1   
5                 0         1        0             0        0             0   
6                 8         0       90             1        0             0   
7                 2         1       90             0        0             0   
8                 1         0       90             0        0             1   
9                 7         1       90             1        0             1   
10                2         0       90             0        0             0   
11                2         1       90             0        0             0   
12                2         0       90             0        0             0   
13                2         0       90             0        0             0   
14                1         1       90             0        0             0   
15                5         1       90             0        1             0   
16                2         0       90             0        0             1   
17                2         0       90             0        0             0   
19                5         1       45             1        0             0   
20                5         0       90             0        1             0   
21                9         1      177             1        0             1   
22                4         1       90             0        1             0   
23                2         0       90             0        0             0   
24                2         1       90             0        0             1   
25                2         0       90             0        0             0   

       goals_conceded  own_goals  penalties_saved  penalties_missed  \
round                                                                 
1                   2          0                0                 1   
2                   1          0                0                 0   
3                   2          0                0                 0   
4                   0          0                0                 0   
5                   0          0                0                 0   
6                   1          0                0                 0   
7                   2          0                0                 0   
8                   0          0                0                 0   
9                   0          0                0                 0   
10                  1          0                0                 0   
11                  2          0                0                 0   
12                  1          0                0                 0   
13                  2          0                0                 0   
14                  1          0                0                 0   
15                  2          0                0                 0   
16                  0          0                0                 0   
17                  2          0                0                 0   
19                  2          0                0                 0   
20                  1          0                0                 0   
21                  2          0                0                 0   
22                  3          0                0                 0   
23                  1          0                0                 0   
24                  0          0                0                 0   
25                  2          0                0                 0   

       yellow_cards  red_cards  saves  bonus  bps  opponent_team_is_1  \
round                           

In [421]:
x=[np.arange(i-9,i+1) for i in range(10,len(new_history)+1)]
x
#x= np.arange(0,10)

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13]),
 array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15]),
 array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17]),
 array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21]),
 array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22]),
 array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23]),
 array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])]

In [422]:
history_slice = new_history.loc[x[0],:].iloc[::-1].reset_index(drop=True)

In [423]:
hist_unstacked = history_slice.unstack().to_frame().T
hist_unstacked.columns = hist_unstacked.columns.map(lambda x: x[0] + '_' + str(1+x[1])+'_weeks_ago')
hist_unstacked

total_points_1_weeks_ago  total_points_2_weeks_ago  \
0                       2.0                       7.0   

   total_points_3_weeks_ago  total_points_4_weeks_ago  \
0                       1.0                       2.0   

   total_points_5_weeks_ago  total_points_6_weeks_ago  \
0                       8.0                       0.0   

   total_points_7_weeks_ago  total_points_8_weeks_ago  \
0                      -1.0                      11.0   

   total_points_9_weeks_ago  total_points_10_weeks_ago  was_home_1_weeks_ago  \
0                      16.0                       13.0                   0.0   

   was_home_2_weeks_ago  was_home_3_weeks_ago  was_home_4_weeks_ago  \
0                   1.0                   0.0                   1.0   

   was_home_5_weeks_ago  was_home_6_weeks_ago  was_home_7_weeks_ago  \
0                   0.0                   1.0                   0.0   

   was_home_8_weeks_ago  was_home_9_weeks_ago  was_home_10_weeks_ago  \
0                   1.0                   1.0                    0.0   

   minutes_1_weeks_ago  minutes_2_weeks_ago  minutes_3_weeks_ago  \
0                 90.0                 90.0                 90.0   

   minutes_4_weeks_ago  minutes_5_weeks_ago  minutes_6_weeks_ago  \
0                 90.0                 90.0                  0.0   

   minutes_7_weeks_ago  minutes_8_weeks_ago  minutes_9_weeks_ago  \
0                 90.0                 90.0                 88.0   

   minutes_10_weeks_ago  goals_scored_1_weeks_ago  goals_scored_2_weeks_ago  \
0                  90.0                       0.0                       1.0   

   goals_scored_3_weeks_ago  goals_scored_4_weeks_ago  \
0                       0.0                       0.0   

   goals_scored_5_weeks_ago  goals_scored_6_weeks_ago  \
0                       1.0                       0.0   

   goals_scored_7_weeks_ago  goals_scored_8_weeks_ago  \
0                       0.0                       1.0   

   goals_scored_9_weeks_ago  goals_scored_10_weeks_ago  assists_1_weeks_ago  \
0                       2.0                        1.0                  0.0   

   assists_2_weeks_ago  assists_3_weeks_ago  assists_4_weeks_ago  \
0                  0.0                  0.0                  0.0   

   assists_5_weeks_ago  assists_6_weeks_ago  assists_7_weeks_ago  \
0                  0.0                  0.0                  0.0   

   assists_8_weeks_ago  assists_9_weeks_ago  assists_10_weeks_ago  \
0                  1.0                  1.0                   2.0   

   clean_sheets_1_weeks_ago  clean_sheets_2_weeks_ago  \
0                       0.0                       1.0   

   clean_sheets_3_weeks_ago  clean_sheets_4_weeks_ago  \
0                       1.0                       0.0   

   clean_sheets_5_weeks_ago  clean_sheets_6_weeks_ago  \
0                       0.0                       0.0   

   clean_sheets_7_weeks_ago  clean_sheets_8_weeks_ago  \
0                       1.0                       0.0   

   clean_sheets_9_weeks_ago  clean_sheets_10_weeks_ago  \
0                       0.0                        0.0   

   goals_conceded_1_weeks_ago  goals_conceded_2_weeks_ago  \
0                         1.0                         0.0   

   goals_conceded_3_weeks_ago  goals_conceded_4_weeks_ago  \
0                         0.0                         2.0   

   goals_conceded_5_weeks_ago  goals_conceded_6_weeks_ago  \
0                         1.0                         0.0   

   goals_conceded_7_weeks_ago  goals_conceded_8_weeks_ago  \
0                         0.0                         2.0   

   goals_conceded_9_weeks_ago  goals_conceded_10_weeks_ago  \
0                         1.0                          2.0   

   own_goals_1_weeks_ago  own_goals_2_weeks_ago  own_goals_3_weeks_ago  \
0                    0.0                    0.0                    0.0   

   own_goals_4_weeks_ago  own_goals_5_weeks_ago  own_goals_6_weeks_ago  \
0                    0.0                    0.0

In [436]:
new_history.loc[max(x[0])+1,:]['total_points']

2.0

In [438]:
hist_unstacked['target'] = new_history.loc[max(x[0])+1,:]['total_points']
hist_unstacked

total_points_1_weeks_ago  total_points_2_weeks_ago  \
0                       2.0                       7.0   

   total_points_3_weeks_ago  total_points_4_weeks_ago  \
0                       1.0                       2.0   

   total_points_5_weeks_ago  total_points_6_weeks_ago  \
0                       8.0                       0.0   

   total_points_7_weeks_ago  total_points_8_weeks_ago  \
0                      -1.0                      11.0   

   total_points_9_weeks_ago  total_points_10_weeks_ago  was_home_1_weeks_ago  \
0                      16.0                       13.0                   0.0   

   was_home_2_weeks_ago  was_home_3_weeks_ago  was_home_4_weeks_ago  \
0                   1.0                   0.0                   1.0   

   was_home_5_weeks_ago  was_home_6_weeks_ago  was_home_7_weeks_ago  \
0                   0.0                   1.0                   0.0   

   was_home_8_weeks_ago  was_home_9_weeks_ago  was_home_10_weeks_ago  \
0                   1.0                   1.0                    0.0   

   minutes_1_weeks_ago  minutes_2_weeks_ago  minutes_3_weeks_ago  \
0                 90.0                 90.0                 90.0   

   minutes_4_weeks_ago  minutes_5_weeks_ago  minutes_6_weeks_ago  \
0                 90.0                 90.0                  0.0   

   minutes_7_weeks_ago  minutes_8_weeks_ago  minutes_9_weeks_ago  \
0                 90.0                 90.0                 88.0   

   minutes_10_weeks_ago  goals_scored_1_weeks_ago  goals_scored_2_weeks_ago  \
0                  90.0                       0.0                       1.0   

   goals_scored_3_weeks_ago  goals_scored_4_weeks_ago  \
0                       0.0                       0.0   

   goals_scored_5_weeks_ago  goals_scored_6_weeks_ago  \
0                       1.0                       0.0   

   goals_scored_7_weeks_ago  goals_scored_8_weeks_ago  \
0                       0.0                       1.0   

   goals_scored_9_weeks_ago  goals_scored_10_weeks_ago  assists_1_weeks_ago  \
0                       2.0                        1.0                  0.0   

   assists_2_weeks_ago  assists_3_weeks_ago  assists_4_weeks_ago  \
0                  0.0                  0.0                  0.0   

   assists_5_weeks_ago  assists_6_weeks_ago  assists_7_weeks_ago  \
0                  0.0                  0.0                  0.0   

   assists_8_weeks_ago  assists_9_weeks_ago  assists_10_weeks_ago  \
0                  1.0                  1.0                   2.0   

   clean_sheets_1_weeks_ago  clean_sheets_2_weeks_ago  \
0                       0.0                       1.0   

   clean_sheets_3_weeks_ago  clean_sheets_4_weeks_ago  \
0                       1.0                       0.0   

   clean_sheets_5_weeks_ago  clean_sheets_6_weeks_ago  \
0                       0.0                       0.0   

   clean_sheets_7_weeks_ago  clean_sheets_8_weeks_ago  \
0                       1.0                       0.0   

   clean_sheets_9_weeks_ago  clean_sheets_10_weeks_ago  \
0                       0.0                        0.0   

   goals_conceded_1_weeks_ago  goals_conceded_2_weeks_ago  \
0                         1.0                         0.0   

   goals_conceded_3_weeks_ago  goals_conceded_4_weeks_ago  \
0                         0.0                         2.0   

   goals_conceded_5_weeks_ago  goals_conceded_6_weeks_ago  \
0                         1.0                         0.0   

   goals_conceded_7_weeks_ago  goals_conceded_8_weeks_ago  \
0                         0.0                         2.0   

   goals_conceded_9_weeks_ago  goals_conceded_10_weeks_ago  \
0                         1.0                          2.0   

   own_goals_1_weeks_ago  own_goals_2_weeks_ago  own_goals_3_weeks_ago  \
0                    0.0                    0.0                    0.0   

   own_goals_4_weeks_ago  own_goals_5_weeks_ago  own_goals_6_weeks_ago  \
0                    0.0                    0.0

In [ ]:
hist_unstacked.to_dict('records')[0]

{'total_points_fixture_0': 1,
 'total_points_fixture_1': 2,
 'total_points_fixture_2': 1,
 'total_points_fixture_3': 0,
 'total_points_fixture_4': 0,
 'total_points_fixture_5': 0,
 'total_points_fixture_6': 0,
 'total_points_fixture_7': 0,
 'total_points_fixture_8': 0,
 'total_points_fixture_9': 0,
 'total_points_fixture_10': 0,
 'total_points_fixture_11': 0,
 'total_points_fixture_12': 0,
 'total_points_fixture_13': 0,
 'total_points_fixture_14': 0,
 'total_points_fixture_15': 0,
 'total_points_fixture_16': 0,
 'total_points_fixture_17': 0,
 'total_points_fixture_18': 0,
 'total_points_fixture_19': 0,
 'total_points_fixture_20': 0,
 'total_points_fixture_21': 0,
 'was_home_fixture_0': False,
 'was_home_fixture_1': True,
 'was_home_fixture_2': False,
 'was_home_fixture_3': True,
 'was_home_fixture_4': False,
 'was_home_fixture_5': True,
 'was_home_fixture_6': False,
 'was_home_fixture_7': True,
 'was_home_fixture_8': True,
 'was_home_fixture_9': False,
 'was_home_fixture_10': True,
 'w