# Analysis Notebook

In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_json('.data/joined_data.json').set_index('index')

# Find players with Null chance of playing
df_left = df[df['chance_of_playing_next_round'] == df['chance_of_playing_next_round'].isna()]

# Of the players who are null chance of playing find the injuries and remove them from rows to drop
injuries = []
for player in df_left.iterrows():
    if ('injury' in player[1]['news'].lower() or 'suspended' in player[1]['news'].lower()) and 'unknown ' not in player[1]['news'].lower():
        injuries.append(player[0])

df_left = df_left.drop(index=injuries)

# drop the players who are not injured or suspended eg. have left the club...
df = df.drop(index=df_left.index)

# Add custom injury dummy variables
# Created my own dummy variables
df['75%'] = df['news'].str.contains('75%')*1
df['50%'] = df['news'].str.contains('50%')*1
df['25%'] = df['news'].str.contains('25%')*1

df['unknown'] = df['news'].str.lower().str.contains('unknown%')*1
df['expected_back'] = df['news'].str.lower().str.contains('expected back')*1
df['suspended'] = df['news'].str.lower().str.contains('suspended')*1

df = df.drop(['news','news_added'], axis=1)

In [3]:
df

chance_of_playing_next_round  chance_of_playing_this_round  \
index                                                               
1                              75.0                          75.0   
5                             100.0                         100.0   
6                             100.0                         100.0   
7                             100.0                         100.0   
12                            100.0                         100.0   
...                             ...                           ...   
475                             NaN                           NaN   
547                             NaN                           NaN   
583                           100.0                          75.0   
685                             NaN                           NaN   
689                             NaN                           NaN   

       dreamteam_count  element_type  event_points  form  in_dreamteam  \
index                                                                    
1                    0             1             0   0.0         False   
5                    0             2             0   3.0         False   
6                    1             4             0   3.5         False   
7                    0             3             0   1.0         False   
12                   0             3             0   0.0         False   
...                ...           ...           ...   ...           ...   
475                  4             1            10   4.3         False   
547                  0             3             3   1.0         False   
583                  1             4             1   0.3         False   
685                  0             2             0   0.3         False   
689                  0             3             0   0.3         False   

       now_cost  points_per_game  selected_by_percent status  team  \
index                                                                
1            45              1.3                  0.8      d     1   
5            42              1.6                  0.2      a     1   
6            83              3.1                  4.5      a     1   
7            48              1.8                  0.3      a     1   
12           44              1.6                  0.3      a     1   
...         ...              ...                  ...    ...   ...   
475          52              4.7                  7.6      a    20   
547          44              2.0                  0.1      a    20   
583          54              3.2                  2.5      a    20   
685          45              1.5                  0.0      a    20   
689          55              1.0                  0.0      a    20   

       total_points  transfers_in  transfers_out  value_form  value_season  \
index                                                                        
1                 4         63640         188156         0.0           0.9   
5                 8         14748          26229         0.7           1.9   
6                53        967727         810760         0.4           6.4   
7                20         26690          86255         0.2           4.2   
12               11         35304          71433         0.0           2.5   
...             ...           ...            ...         ...           ...   
475             108       1095942         522312         0.8          20.8   
547               4         11358          10872         0.2           0.9   
583              48       1732414        1596323         0.1           8.9   
685               3           324            170         0.1           0.7   
689               1           394            171         0.1           0.2   

       minutes  goals_scored  assists  clean_sheets  goals_conceded  \
index                                                                 
1          270             0        0             0               9   
5      

In [4]:
sadkfjklfjlk

NameError: name 'sadkfjklfjlk' is not defined

In [ ]:
to_drop = [#'chance_of_playing_next_round', 'chance_of_playing_this_round',
       'dreamteam_count',
       # 'element_type',
       'event_points', 'form',
       'in_dreamteam', 'now_cost', 'points_per_game', 'selected_by_percent',
       'status', 'team',
       'total_points', #THIS COLUMN IS A LITTLE BIT NAUGHTY AS GIVE HINT INTO FUTURE using cumsum instead
       'transfers_in', 'transfers_out',
       'value_form', 'value_season', 'minutes', 'goals_scored', 'assists',
       'clean_sheets', 'goals_conceded', 'own_goals', 'penalties_saved',
       'penalties_missed', 'yellow_cards', 'red_cards', 'saves', 'bonus',
       'bps', 'influence', 'creativity', 'threat', 'ict_index',
       #'influence_rank', 'creativity_rank', 'threat_rank', 'ict_index_rank',
       #'corners_and_indirect_freekicks_order', 'direct_freekicks_order',
       #'penalties_order', 'player_name',
       'games',

       # Need to drop these columns for time being as they give ML model a hint into future
       'xG', 'xA', 'shots', 'key_passes', 'npg', 'npxG', 'xGChain', 'xGBuildup',
       '75%', '50%', '25%', 'unknown', 'expected_back', 'suspended'
       ]
df = df.drop(columns=to_drop)
df

chance_of_playing_next_round  chance_of_playing_this_round  \
index                                                               
1                              75.0                          75.0   
5                             100.0                         100.0   
6                             100.0                         100.0   
7                             100.0                         100.0   
12                            100.0                         100.0   
...                             ...                           ...   
475                             NaN                           NaN   
547                             NaN                           NaN   
583                           100.0                          75.0   
685                             NaN                           NaN   
689                             NaN                           NaN   

       element_type  influence_rank  creativity_rank  threat_rank  \
index                                                               
1                 1             351              590          569   
5                 2             391              286          416   
6                 4             173               93           50   
7                 3             289              177          259   
12                3             396              290          404   
...             ...             ...              ...          ...   
475               1               7              347          680   
547               3             465              381          546   
583               4             231              186          120   
685               2             400              432          640   
689               3             470              380          332   

       ict_index_rank  corners_and_indirect_freekicks_order  \
index                                                         
1                 413                                   NaN   
5                 393                                   NaN   
6                  65                                   NaN   
7                 263                                   NaN   
12                391                                   NaN   
...               ...                                   ...   
475               154                                   NaN   
547               459                                   4.0   
583               189                                   NaN   
685               436                                   NaN   
689               428                                   NaN   

       direct_freekicks_order  penalties_order                     player_name  
index                                                                           
1                         NaN              NaN                      Bernd Leno  
5                         NaN              NaN                   Cédric Soares  
6                         NaN              2.0             Alexandre Lacazette  
7                         4.0              NaN                    Granit Xhaka  
12                        NaN              NaN   Mohamed Naser El Sayed Elneny  
...                       ...              ...                             ...  
475                       NaN              NaN             José Malheiro de Sá  
547                       NaN              NaN                     Luke Cundle  
583                       NaN              NaN                  Hee-Chan Hwang  
685                       NaN              NaN              Toti António Gomes  
689                       NaN              NaN  Francisco Jorge Tomás Oliveira  

[444 rows x 11 columns]

In [ ]:
id=1
history = pd.DataFrame(hist_data[id]['history'])

# Create team columns
team_cols = {i:'opponent_team_is_'+str(i) for i in np.arange(1,21)}
history[list(team_cols.values())] = 0
opponent_dummies = pd.get_dummies(history['opponent_team']).rename(columns=team_cols)
history[list(opponent_dummies.columns)] = opponent_dummies

# Get fixture difficulty
history = pd.concat([history,get_difficulty(team_df=team_df, history=history)], axis=1)

# Goals for and against
history['goals_for'] = history['team_h_score'].where(history['was_home'], history['team_a_score'])
history['goals_against'] = history['team_a_score'].where(history['was_home'], history['team_h_score'])

# Drop irrelevant columns
history = history.drop(columns=['team_h_score','team_a_score','element','fixture','kickoff_time','opponent_team'])

# groupBY sum gameweeks
mean_cols =['value', 'transfers_balance', 'selected', 'transfers_in','transfers_out','opponent_strength', 'opponent_strength_overall',
    'opponent_strength_attack', 'opponent_strength_defence']
history = pd.concat([history.groupby('round').sum().drop(columns=mean_cols), history.groupby('round')[mean_cols].mean()], axis=1)

# Finding empty gameweeks
for empty_gw in np.arange(1,max(history.index)):
    if i not in history.index:
        history.loc[empty_gw] = None
history = history.sort_index()

# filling interpolated transfer data or zeros for gw data
history[['value', 'transfers_balance', 'selected','transfers_in', 'transfers_out']] = \
    history[['value', 'transfers_balance', 'selected', 'transfers_in', 'transfers_out']].interpolate(method='linear')
history = history.fillna(0)

# Adding a cumulative sum of points
history['points_cumsum'] = history['total_points'].cumsum()

# Adding general player data 
history['id'] = id
player_df = pd.merge(left=history, right=df, left_on='id', right_index=True)

player_df

total_points  was_home  minutes  goals_scored  assists  clean_sheets  \
round                                                                         
1                 1         0       90             0        0             0   
2                 2         1       90             0        0             0   
3                 1         0       90             0        0             0   
4                 0         1        0             0        0             0   
5                 0         0        0             0        0             0   
6                 0         1        0             0        0             0   
7                 0         0        0             0        0             0   
8                 0         1        0             0        0             0   
9                 0         1        0             0        0             0   
10                0         0        0             0        0             0   
11                0         1        0             0        0             0   
12                0         0        0             0        0             0   
13                0         1        0             0        0             0   
14                0         0        0             0        0             0   
15                0         0        0             0        0             0   
16                0         1        0             0        0             0   
17                0         1        0             0        0             0   
18                0         0        0             0        0             0   
19                0         0        0             0        0             0   
21                0         1        0             0        0             0   
23                0         1        0             0        0             0   
24                0         0        0             0        0             0   

       goals_conceded  own_goals  penalties_saved  penalties_missed  \
round                                                                 
1                   2          0                0                 0   
2                   2          0                0                 0   
3                   5          0                0                 0   
4                   0          0                0                 0   
5                   0          0                0                 0   
6                   0          0                0                 0   
7                   0          0                0                 0   
8                   0          0                0                 0   
9                   0          0                0                 0   
10                  0          0                0                 0   
11                  0          0                0                 0   
12                  0          0                0                 0   
13                  0          0                0                 0   
14                  0          0                0                 0   
15                  0          0                0                 0   
16                  0          0                0                 0   
17                  0          0                0                 0   
18                  0          0                0                 0   
19                  0          0                0                 0   
21                  0          0                0                 0   
23                  0          0                0                 0   
24                  0          0                0                 0   

       yellow_cards  red_cards  saves  bonus  bps  opponent_team_is_1  \
round                                                                   
1                 0          0      1      0   11                   0   
2                 0          0      3      0   17                   0   
3                 0          0      5      0   20                   0   
4                 0          0      0   

## Fixture difficulty

In [ ]:
# FUNCTION
import requests
url = "https://fantasy.premierleague.com/api/bootstrap-static/"

response = requests.get(url)
team_df = pd.DataFrame(response.json()['teams']).set_index('id').drop(columns=[
       'code', 'draw', 'form',
       # 'id',
       'loss', 'name', 'played', 'points',
       'position', 'short_name',
       # 'strength', 
       'team_division', 'unavailable',
       'win',
       #'strength_overall_home', 'strength_overall_away',
       #'strength_attack_home', 'strength_attack_away', 'strength_defence_home',
       #'strength_defence_away',
       'pulse_id'])

In [ ]:
def get_difficulty(team_df, history):
    oppenent_home = team_df.loc[history['opponent_team'],['strength', 'strength_overall_home',
       'strength_attack_home', 'strength_defence_home']]
    oppenent_home.columns = oppenent_home.columns.map(lambda x : 'opponent_' + '_'.join(x.split('_')[0:2]))

    oppenent_away = team_df.loc[history['opponent_team'],['strength', 'strength_overall_away',
       'strength_attack_away', 'strength_defence_away']]
    oppenent_away.columns = oppenent_away.columns.map(lambda x : 'opponent_' + '_'.join(x.split('_')[0:2]))

    return oppenent_home.where(history['was_home'], oppenent_away).reset_index().drop(columns=['id'])

# Function for building dataset

In [ ]:
import json

with open('.data/history.json', 'r') as f:
  hist_data = json.load(f)
  # ensuring player id is an integer
hist_data = {int(key):value for key,value in hist_data.items()}

In [ ]:
# ensuring player id is an integer
hist_data = {int(key):value for key,value in hist_data.items()}

In [ ]:
data_points = []

for id in df.index:
    history = pd.DataFrame(hist_data[id]['history'])

    # Create team columns
    team_cols = {i:'opponent_team_is_'+str(i) for i in np.arange(1,21)}
    history[list(team_cols.values())] = 0
    opponent_dummies = pd.get_dummies(history['opponent_team']).rename(columns=team_cols)
    history[list(opponent_dummies.columns)] = opponent_dummies

    # Get fixture difficulty
    history = pd.concat([history,get_difficulty(team_df=team_df, history=history)], axis=1)

    # Goals for and against
    history['goals_for'] = history['team_h_score'].where(history['was_home'], history['team_a_score'])
    history['goals_against'] = history['team_a_score'].where(history['was_home'], history['team_h_score'])

    # Drop irrelevant columns
    history = history.drop(columns=['team_h_score','team_a_score','element','fixture','kickoff_time','opponent_team'])

    # groupBY sum gameweeks
    mean_cols =['value', 'transfers_balance', 'selected', 'transfers_in','transfers_out','opponent_strength', 'opponent_strength_overall',
        'opponent_strength_attack', 'opponent_strength_defence']
    history = pd.concat([history.groupby('round').sum().drop(columns=mean_cols), history.groupby('round')[mean_cols].mean()], axis=1)

    # Finding empty gameweeks
    for empty_gw in np.arange(1,max(history.index)):
        if empty_gw not in history.index:
            history.loc[empty_gw] = None
    history = history.sort_index()

    # filling interpolated transfer data or zeros for gw data
    history[['value', 'transfers_balance', 'selected','transfers_in', 'transfers_out']] = \
        history[['value', 'transfers_balance', 'selected', 'transfers_in', 'transfers_out']].interpolate(method='linear')
    history = history.fillna(0)

    # Adding a cumulative sum of points
    history['points_cumsum'] = history['total_points'].cumsum()

    # Adding general player data 
    player_df = history

    # Split the data
    slices = [np.arange(i-2,i+1) for i in range(3,len(player_df))]
    for slice in slices:
        df_slice = player_df.loc[slice,:].iloc[::-1].reset_index(drop=True)
        
        unstacked = df_slice.unstack().to_frame().T
        unstacked.columns = unstacked.columns.map(lambda x: x[0] + '_' + str(1+x[1])+'_weeks_ago')

        unstacked['id'] = id
        unstacked['target'] = history.loc[max(slice)+1,:]['total_points']
        data_points.append(unstacked.to_dict('records')[0])

In [ ]:
print(f"{len(data_points)} data points to train on")

9700 data points to train on


In [ ]:
pd.DataFrame(data_points)['id']

0         1
1         1
2         1
3         1
4         1
       ... 
9695    689
9696    689
9697    689
9698    689
9699    689
Name: id, Length: 9700, dtype: int64

In [ ]:
data = pd.merge(left=pd.DataFrame(data_points), right=df, left_on='id', right_index=True)
data.sample(10)

total_points_1_weeks_ago  total_points_2_weeks_ago  \
7710                       1.0                       2.0   
4319                       0.0                       2.0   
6290                       2.0                       0.0   
7529                       1.0                       5.0   
4754                       0.0                       0.0   
3538                       1.0                       0.0   
1173                       0.0                       0.0   
2546                       2.0                       6.0   
6675                       0.0                       0.0   
239                        3.0                       6.0   

      total_points_3_weeks_ago  was_home_1_weeks_ago  was_home_2_weeks_ago  \
7710                       2.0                   1.0                   1.0   
4319                       6.0                   0.0                   1.0   
6290                       0.0                   1.0                   1.0   
7529                       3.0                   0.0                   1.0   
4754                       0.0                   0.0                   0.0   
3538                       0.0                   1.0                   0.0   
1173                       1.0                   1.0                   0.0   
2546                       6.0                   1.0                   0.0   
6675                       1.0                   1.0                   0.0   
239                        2.0                   1.0                   0.0   

      was_home_3_weeks_ago  minutes_1_weeks_ago  minutes_2_weeks_ago  \
7710                   0.0                  9.0                 73.0   
4319                   0.0                  0.0                 90.0   
6290                   0.0                 90.0                  0.0   
7529                   1.0                 10.0                 90.0   
4754                   0.0                  0.0                  0.0   
3538                   1.0                 55.0                  0.0   
1173                   1.0                  0.0                  0.0   
2546                   1.0                 90.0                 90.0   
6675                   1.0                  0.0                  0.0   
239                    1.0                 90.0                 84.0   

      minutes_3_weeks_ago  goals_scored_1_weeks_ago  goals_scored_2_weeks_ago  \
7710                 90.0                       0.0                       0.0   
4319                 87.0                       0.0                       0.0   
6290                 45.0                       0.0                       0.0   
7529                 90.0                       0.0                       0.0   
4754                  0.0                       0.0                       0.0   
3538                  0.0                       0.0                       0.0   
1173                 90.0                       0.0                       0.0   
2546                 90.0                       0.0                       0.0   
6675                 19.0                       0.0                       0.0   
239                  90.0                       0.0                       0.0   

      goals_scored_3_weeks_ago  assists_1_weeks_ago  assists_2_weeks_ago  \
7710                       0.0                  0.0                  0.0   
4319                       1.0                  0.0                  0.0   
6290                       0.0                  0.0                  0.0   
7529                       0.0                  0.0                  1.0   
4754                       0.0                  0.0                  0.0   
3538                       0.0                  0.0                  0.0   
1173                       0.0                  0.0                  0.0   
2546                       0.0                  0.0                  0.0   
6675                       0.0                  0.0                  0.0   
239                        0.0           

In [ ]:
data.to_pickle('data')

In [ ]:
slices = [np.arange(i-2,i+1) for i in range(3,len(player_df))]
slices

[array([1, 2, 3]),
 array([2, 3, 4]),
 array([3, 4, 5]),
 array([4, 5, 6]),
 array([5, 6, 7]),
 array([6, 7, 8]),
 array([7, 8, 9]),
 array([ 8,  9, 10]),
 array([ 9, 10, 11]),
 array([10, 11, 12]),
 array([11, 12, 13]),
 array([12, 13, 14]),
 array([13, 14, 15]),
 array([14, 15, 16]),
 array([15, 16, 17]),
 array([16, 17, 18]),
 array([17, 18, 19]),
 array([18, 19, 20]),
 array([19, 20, 21]),
 array([20, 21, 22]),
 array([21, 22, 23]),
 array([22, 23, 24])]